### PR TITLE
fix(auction-salt): random int is not a function in browser env

### LINKED ISSUE #26: randomInt is not a function
When calling `sdk.PlaceOrder()` it's throwing 

Screenshot 2023-04-10 at 8 11 30 PM

I ran it on node versions 16 and 19.

### PR DESCRIPTION
**Pull request by frolovdev**
closes #26

### CODE REVIEW

File: src/auction-salt/auction-salt.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ export class AuctionSalt {
             throw new Error('salt should be less 18 bytes')
         }
 
-        this.salt = auction.salt || randomInt(10000).toString()
+        this.salt = auction.salt || randomIntString(5)
```
Comment (frolovdev) [inline src/auction-salt/auction-salt.ts:30]: 📓 the salt is 144 bit because

```
uint256 private constant _SALT_MASK              = 0x0000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF; // prettier-ignore
```

0x0000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
which in binary

Screenshot 2023-04-11 at 09 20 15

which means the max value is 2^144 -1, which is far far away from out current function

**Review by krboktv — APPROVED** [review]
